services:
  postgres:
    image: postgres:16
    container_name: nestjs-postgres-${NODE_ENV:-local}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data-${NODE_ENV:-local}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nestjs-network

volumes:
  postgres-data-local:
  postgres-data-staging:
  postgres-data-production:
networks:
  nestjs-network:
    driver: bridge
